In [2]:
!bash get_datasets.sh

--2021-08-08 18:07:50--  http://cs231n.stanford.edu/coco_captioning.zip
Resolving cs231n.stanford.edu (cs231n.stanford.edu)... 171.64.68.10
Connecting to cs231n.stanford.edu (cs231n.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1035210391 (987M) [application/zip]
Saving to: ‘coco_captioning.zip’

coco_captioning.zip  61%[===========>        ] 610.08M   934KB/s    in 11m 10s 

2021-08-08 18:19:06 (932 KB/s) - Connection closed at byte 639720295. Retrying.

--2021-08-08 18:19:07--  (try: 2)  http://cs231n.stanford.edu/coco_captioning.zip
Connecting to cs231n.stanford.edu (cs231n.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 1035210391 (987M), 395490096 (377M) remaining [application/zip]
Saving to: ‘coco_captioning.zip’

coco_captioning.zip 100%[++++++++++++=======>] 987.25M  1.06MB/s    in 6m 54s  

2021-08-08 18:26:01 (932 KB/s) - ‘coco_captioning.zip’ saved [10352103

In [2]:
!wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz

--2021-08-13 17:58:09--  http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Resolving yann.lecun.com (yann.lecun.com)... 2606:4700:3034::6815:1d24, 2606:4700:3036::ac43:ab4c, 104.21.29.36, ...
Connecting to yann.lecun.com (yann.lecun.com)|2606:4700:3034::6815:1d24|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9912422 (9.5M) [application/x-gzip]
Saving to: ‘train-images-idx3-ubyte.gz’

e.gz                  6%[>                   ] 617.33K  33.3KB/s    eta 4m 42s ^C


In [7]:
import numpy as np
a = np.array([1,2,3,4,5])

In [8]:
a[::-1]

array([5, 4, 3, 2, 1])

In [9]:
a[::2]

array([1, 3, 5])

In [10]:
a  = [1,2,3,4,5]

In [12]:
a[::-1]

[5, 4, 3, 2, 1]

In [3]:
import torch

In [5]:
(torch.rand(2,3) - 0.5)*2

tensor([[ 0.3676, -0.1217,  0.2378],
        [ 0.1307,  0.3015,  0.6606]])

In [14]:
a = torch.Tensor([1,2,3])
torch.log(a)

tensor([0.0000, 0.6931, 1.0986])

In [8]:
torch.ones_like(a
               )

tensor([1., 1., 1.])

In [9]:
a=1.11111111111111111

In [13]:
print("a:{:.3f}".format(a))

a:1.111


Object `torch.cpu` not found.


In [19]:
import torch.nn as nn

In [25]:
m = nn.MaxPool2d(2, stride=2)

In [26]:
input = torch.randn(20, 16, 7, 7)

In [27]:
output = m(input)

In [28]:
output.shape

torch.Size([20, 16, 3, 3])

In [43]:
conv1 = 32*5*5*1 + 32
conv2 = 64*5*5*32 + 64
fc1 = 64*4*4*1024 + 64*16
fc2 = 64*16+1
conv1,conv2,fc1,fc2

(832, 51264, 1049600, 1025)

In [44]:
conv1+conv2+fc1+fc2

1102721