In [1]:
import numpy as np

In [2]:
X = np.random.randn(3,4)

In [3]:
X

array([[ 1.04479004, -0.5534274 , -0.95251246,  0.08114134],
       [-1.07739675, -1.42214084,  0.43253424, -0.75783252],
       [ 1.03362835, -1.29394753, -0.46800459, -0.57483033]])

In [4]:
a =np.array([[1,2],
             [3,4]])

In [9]:
X -=np.mean(X,axis=0)

In [12]:
cov = X.T @ X /X.shape[0]

In [13]:
cov.shape

(4, 4)

In [15]:
U,S,V = np.linalg.svd(cov)

In [17]:
S

array([1.44785405e+00, 1.53416309e-01, 3.27538399e-17, 3.04895025e-19])

In [19]:
V

array([[-0.81416447, -0.24036293,  0.47111556, -0.23960802],
       [ 0.48340854, -0.6406071 ,  0.22821671, -0.55123122],
       [ 0.24862357,  0.67830019,  0.61525726, -0.31552127],
       [-0.20405566,  0.26787507, -0.58942833, -0.73428773]])

In [20]:
U

array([[-0.81416447,  0.48340854, -0.03913154,  0.31925086],
       [-0.24036293, -0.6406071 , -0.67577141,  0.27419192],
       [ 0.47111556,  0.22821671, -0.03855379,  0.85116442],
       [-0.23960802, -0.55123122,  0.73506145,  0.31371453]])

In [3]:
!python setup.py build_ext --inplace

Compiling im2col_cython.pyx because it changed.
[1/1] Cythonizing im2col_cython.pyx
/home/zhangshengyu/software/anaconda3/envs/deviceCloud/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /share/home/zhangshengyu/ziqijiang/CS231n/assignment2/cs231n/im2col_cython.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'im2col_cython' extension
creating build
creating build/temp.linux-x86_64-3.9
gcc -pthread -B /home/zhangshengyu/software/anaconda3/envs/deviceCloud/compiler_compat -Wl,--sysroot=/ -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/zhangshengyu/software/anaconda3/envs/deviceCloud/include -fPIC -O2 -isystem /home/zhangshengyu/software/anaconda3/envs/deviceCloud/include -fPIC -I/home/zhangshengyu/software/anaconda3/envs/deviceCloud/lib/python3.9/site-packages/numpy/core/include -I/home/zhangs

In [2]:
!proxychains4 pip install Cython

[proxychains] config file found: /home/zhangshengyu/config/proxychains.conf
[proxychains] preloading /home/zhangshengyu/software/proxychains4/lib/libproxychains4.so
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     |████████████████████████████████| 1.9 MB 6.2 MB/s eta 0:00:01
