In [55]:
!unzip assignment3_colab.zip

Archive:  assignment3_colab.zip
  inflating: assignment3/gan-checks.npz  
  inflating: assignment3/requirements.txt  
   creating: assignment3/images/
   creating: assignment3/cs231n/
  inflating: assignment3/style-transfer-checks.npz  
  inflating: assignment3/makepdf.py  
  inflating: assignment3/simclr_sanity_check.key  
  inflating: assignment3/collectSubmission.sh  
  inflating: assignment3/images/kitten.jpg  
  inflating: assignment3/images/simclr_fig2.png  
  inflating: assignment3/images/gan_outputs_pytorch.png  
   creating: assignment3/images/styles/
  inflating: assignment3/images/sky.jpg  
  inflating: assignment3/images/example_styletransfer.png  
  inflating: assignment3/images/styles/the_scream.jpg  
  inflating: assignment3/images/styles/composition_vii.jpg  
  inflating: assignment3/images/styles/tubingen.jpg  
  inflating: assignment3/images/styles/muse.jpg  
  inflating: assignment3/images/styles/starry_night.jpg  
   creating: assignment3/cs231n/simclr/
  inflating:

In [2]:
import numpy as np

In [3]:
!ls

assignment1  assignment1_colab.zip  assignment2_colab.zip  Untitled.ipynb


In [6]:
!rm -rf assignment2/

In [2]:
2**-2

0.25

In [15]:
def foo(a):
    print(id(a))
    a['1'] = 1
    a['2'] = 2

In [54]:
!rm -rf assignment3/s

In [17]:
foo(b)

139633000738624


In [8]:
foo(b)

In [18]:
print(id(b))

139633000738624


In [20]:
a = np.array(range(5*2)).reshape(2,5)

In [19]:
import numpy as np

In [20]:
np.logspace(-4, 0, num=20)

array([1.00000000e-04, 1.62377674e-04, 2.63665090e-04, 4.28133240e-04,
       6.95192796e-04, 1.12883789e-03, 1.83298071e-03, 2.97635144e-03,
       4.83293024e-03, 7.84759970e-03, 1.27427499e-02, 2.06913808e-02,
       3.35981829e-02, 5.45559478e-02, 8.85866790e-02, 1.43844989e-01,
       2.33572147e-01, 3.79269019e-01, 6.15848211e-01, 1.00000000e+00])

In [21]:
np.random.rand?

In [22]:
def rng_n():
    np.random.seed(123)
    for i in range(5):
        print(np.random.rand(4))


In [23]:
rng_n()

[0.69646919 0.28613933 0.22685145 0.55131477]
[0.71946897 0.42310646 0.9807642  0.68482974]
[0.4809319  0.39211752 0.34317802 0.72904971]
[0.43857224 0.0596779  0.39804426 0.73799541]
[0.18249173 0.17545176 0.53155137 0.53182759]


In [32]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
a=np.array([1,2,3,4,5,6,7])

In [21]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
a =np.array(range(2*3*4*5)).reshape((2,3,4,5))

In [30]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [34]:
x = np.array([[1,2],
             [3,4]])

In [38]:
a = a.reshape(5,2)

In [44]:
a[[1,2]]

array([[2, 3],
       [4, 5]])

In [57]:
class MyDataset(Dataset):
    
    def __init__(self):
        txt_data = np.load

In [58]:
a = torch.randn(1,2)

In [59]:
a

tensor([[ 0.2374, -1.4312]])

In [60]:
b = torch.Tensor(range(4)).view(2,2)

In [61]:
b

tensor([[0., 1.],
        [2., 3.]])

In [62]:
a = b

In [63]:
a

tensor([[0., 1.],
        [2., 3.]])

In [68]:
torch.matmul(a,b)

tensor([[ 2.,  3.],
        [ 6., 11.]])

In [67]:
a @ b 

tensor([[ 2.,  3.],
        [ 6., 11.]])

In [3]:
import torch
a = torch.Tensor(range(6)).reshape(2,3)

In [4]:
a

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [5]:
b = torch.Tensor([1,2,3])

In [6]:
b.shape

torch.Size([3])

In [7]:
import numpy as np

In [8]:
a = np.array(range(6)).reshape(2,3)

In [9]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b = np.array([1,2,3])

In [12]:
a.shape,b.shape

((2, 3), (3,))

In [13]:
a + b

array([[1, 3, 5],
       [4, 6, 8]])

In [14]:
np.tanh(a)

array([[0.        , 0.76159416, 0.96402758],
       [0.99505475, 0.9993293 , 0.9999092 ]])

In [17]:
list(reversed([1,2,3]))

[3, 2, 1]

In [18]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [19]:
list(range(9,0,-1))

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [47]:
np.add.at?

In [48]:
a = np.array([1,2,3,4,5,6])

In [51]:
b = np.array([1,2,3,4,5,6])
x = np.array([1,3,4])

In [52]:
np.add.at(a,x,b[x])

In [53]:
a

array([ 1,  4,  3,  8, 10,  6])